### ISSUE TITLE
javscript_sdk_latest link

### ISSUE THREAD

**Issue by mbeck-sans** [contentstack/contentstack-javascript#50]
Not sure if intentional or not, but https://contentstack.com/docs/platforms/javascript-browser/javascript_sdk_latest mentioned in the readme appears to link to v3.11.0, not the latest release.

**Comment by uttamukkoji** [comment]
Thanks @mbeck-sans for raising issue, We will check this on our side, and update you once we resolve issue.

**Comment by uttamukkoji** [comment]
Hi @mbeck-sans ,

Here is the link for min file of new version we release today with the fix for IE11: https://assets.contentstack.io/v3/assets/blt23180bf2502c7444/blt7c37c3a74961a31e/60794c381898af75a401dae0/contentstack-v3.13.1.min.js.

Closing this issue for now. If you have any concern or issue you can re-open or create new issue on Contentstack JS repository.
